import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import ReactQueryProvider from "@/context/ReactQueryProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en">
      <body
        className={`min-h-screen bg-stone-50 text-neutral-800 font-sans flex flex-col ${geistSans.variable} ${geistMono.variable} antialiased `}
        suppressHydrationWarning 
      >
        <ReactQueryProvider >
            <Header />
            <div className="flex-grow pb-16 md:pb-0">{children}</div>
            <Footer />
        </ReactQueryProvider>
      </body>
      
    </html>
    
  );
}